// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA223WWgcmynLLGG3ZUk2rp3xPNT8cfcnE',
    appId: '1:164602080782:web:fa4dc57c1b933b08c6165f',
    messagingSenderId: '164602080782',
    projectId: 'capstone-sleep',
    authDomain: 'capstone-sleep.firebaseapp.com',
    storageBucket: 'capstone-sleep.firebasestorage.app',
    measurementId: 'G-5DN3XNY0D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtJ7GtDL8FbrhlmbbqSkXZwcvdqrPvls',
    appId: '1:164602080782:android:7974046b596f372ec6165f',
    messagingSenderId: '164602080782',
    projectId: 'capstone-sleep',
    storageBucket: 'capstone-sleep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqfiaYk6DcseXWMNDPvbQDDVhmLyzYMs',
    appId: '1:164602080782:ios:4c2d38c5857c1438c6165f',
    messagingSenderId: '164602080782',
    projectId: 'capstone-sleep',
    storageBucket: 'capstone-sleep.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqfiaYk6DcseXWMNDPvbQDDVhmLyzYMs',
    appId: '1:164602080782:ios:4c2d38c5857c1438c6165f',
    messagingSenderId: '164602080782',
    projectId: 'capstone-sleep',
    storageBucket: 'capstone-sleep.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA223WWgcmynLLGG3ZUk2rp3xPNT8cfcnE',
    appId: '1:164602080782:web:9af63cfc9c946dddc6165f',
    messagingSenderId: '164602080782',
    projectId: 'capstone-sleep',
    authDomain: 'capstone-sleep.firebaseapp.com',
    storageBucket: 'capstone-sleep.firebasestorage.app',
    measurementId: 'G-M4T3C8VQT3',
  );
}
